

deploy:         Run build & reinstall

build:          Build the signed & aligned apk in release mode

apk-sign:       Sign the apk, create pauline.apk (signed version of 
                pauline-unsigned.apk)

install:        Install the signed APK on the device. Need adb.

reinstall:      Override the current installation. Need adb.

showdevices:    Show available devices. Need adb.

